// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	ID            int32
	Owner         string
	Repo          string
	FullName      string
	Description   pgtype.Text
	Stars         int32
	Forks         int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	LastFetchedAt pgtype.Timestamp
}
