// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllRepositories = `-- name: GetAllRepositories :many
SELECT id, owner, repo, full_name, description, stars, forks, created_at, updated_at, last_fetched_at
FROM repositories
ORDER BY owner, repo
`

func (q *Queries) GetAllRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, getAllRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.FullName,
			&i.Description,
			&i.Stars,
			&i.Forks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepositoryByOwnerAndRepo = `-- name: GetRepositoryByOwnerAndRepo :one
SELECT id, owner, repo, full_name, description, stars, forks, created_at, updated_at, last_fetched_at
FROM repositories
WHERE owner = $1 AND repo = $2
`

type GetRepositoryByOwnerAndRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) GetRepositoryByOwnerAndRepo(ctx context.Context, arg GetRepositoryByOwnerAndRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByOwnerAndRepo, arg.Owner, arg.Repo)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Description,
		&i.Stars,
		&i.Forks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFetchedAt,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :exec
INSERT INTO repositories (owner, repo, full_name, description, stars, forks, created_at, updated_at, last_fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
ON CONFLICT (owner, repo) 
DO UPDATE SET
    full_name = EXCLUDED.full_name,
    description = EXCLUDED.description,
    stars = EXCLUDED.stars,
    forks = EXCLUDED.forks,
    created_at = EXCLUDED.created_at,
    updated_at = NOW(),
    last_fetched_at = NOW()
`

type UpsertRepositoryParams struct {
	Owner       string
	Repo        string
	FullName    string
	Description pgtype.Text
	Stars       int32
	Forks       int32
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) error {
	_, err := q.db.Exec(ctx, upsertRepository,
		arg.Owner,
		arg.Repo,
		arg.FullName,
		arg.Description,
		arg.Stars,
		arg.Forks,
		arg.CreatedAt,
	)
	return err
}
